### ISSUE TITLE
urgent, need 4 artefacts from you

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow10#1]
Hi @SquidPr0Quo 

Can you please push your versions of the following files:
- recording.wav
- score.md
- reflections.md
- patch.vcv

This was due Sunday @ 11:59pm. **Can you have it in before class today?** If it helps you to submit it in time, don't concern yourself so much with the idea of a 'finished state' of each file. I just need your contributions for each one.

**Comment by SquidPr0Quo** [comment]
Real sorry about that. I committed them but I never pushed them. I think
that's how that works. Do you have them now?

**Comment by michaelpalumbo** [comment]
Thanks Andrew. The only change you've pushed, unfortunately, was the one commit for the score.md, see 111f562

Can you take a look at https://github.com/dispersionlab/gitshow/wiki/using-git and commit the remaining files in your repo, i.e.:

```shell
# check that you have modified files
git status

# check your git log for commits you made
git log

# press 'enter' to scroll through the log. press 'q' to exit git log.

# refer to the wiki article i posted in order to commit, pull, and push. thanks!

**Comment by SquidPr0Quo** [comment]
Looking at this page
<https://github.com/dispersionlab/gitshow10/commits/master> it looks like
the changes I made have already been pushed, Is this not right? Because as
of now I have no local changes.

**Comment by michaelpalumbo** [comment]
Ah! I think this is my mistake, sorry for any confusion. Yes I see that you indeed pushed them. Thanks for following up! See you shortly.

**Comment by SquidPr0Quo** [comment]
No worries!
